language: node_js
node_js:
- 10
before_install: rvm install 2.3.6
install:
- bundle install
- npm install
script: gulp build
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
